apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "appchart.fullname" . }}
  labels:
    {{- include "appchart.labels" . | nindent 4 }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
  - secretKey: demo
    remoteRef:
      key: secret/demo
      property: secret