apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-aws-demo
  namespace: external-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: demo-ssm
    kind: SecretStore
  target:
    name: es-aws-demo
  data:
  - secretKey: demo
    remoteRef:
      key: demo