apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-eso
  namespace: external-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: testvault-backend
    kind: ClusterSecretStore
  data:
  - secretKey: demo
    remoteRef:
      key: secret/demo
      property: hello